version: "3.7"

x-app_environment: &app_environment
  environment:
    - DEBUG
    - ALLOWED_HOSTS
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_NAME
    - POSTGRES_USER

services:
  backend:
    build: ./backend
    entrypoint: sh /app/backend/entrypoint.sh
    command: python /app/backend/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app
    ports:
    - 8000:8000
    depends_on:
      - db
      - redis
    <<: *app_environment

  db:
    image: postgres:12-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redisdata:/data


volumes:
  redisdata:
  postgres_data: