version: "3.7"

x-app_environment: &app_environment
  environment:
    - DEBUG
    - ALLOWED_HOSTS
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_NAME
    - POSTGRES_USER

services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    environment:
      - ENVIRONMENT
      - SITE_HOSTS
      - TLS_MODE

  backend:
    build: ./backend
    entrypoint: sh entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./backend:/app
    ports:
    - 8000:8000
    depends_on:
      - db
      - redis
    <<: *app_environment

  db:
    image: postgres:12-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD

  redis:
    image: redis:6.2.6-alpine
    volumes:
      - redisdata:/data

  celery:
    build: ./backend
    command: celery -A app worker -l info -E -B
    depends_on:
      - db
      - redis
    <<: *app_environment


volumes:
  redisdata:
  postgres_data: